name: FTP Deploy to cPanel

on:
  push:
    branches:
      - main  # Change this branch name if you want to deploy from a different branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository so the workflow has access to your code
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Deploy files via FTP to cPanel
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: "ftp.panadero-api.site"
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          server-dir: "/"
          timeout: 180000  # Timeout set to 3 minutes

      # Restart Node App via SSH
      - name: Restart Node App via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}  # Ensure this secret is set to the correct port (e.g., 22)
          script: |
            # Activate the virtual environment and move to your app directory
            cd /home/areawcmk/apiv4
            # Restart the Node application using PM2 by referencing its file name.
            pm2 restart server.js
