name: FTP Deploy to cPanel

on:
  push:
    branches:
      - main # Change this branch if needed

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Deploy files via FTP to cPanel
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: "ftp.area51.ph"
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"
          server-dir: "/"

      # Restart Node App via SSH
      - name: Restart Node App via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }} # Set this secret to the correct port (e.g., 22)
          script: |
            # (Optionally) Activate the virtual environment for your Node version management
            cloudlinux-selector restart --json --interpreter nodejs --user areawcmk --app-root /home/areawcmk/apiv4
